### ISSUE TITLE
Get predictions as a set of segments

### ISSUE THREAD

**Issue by palandlom** [trzy/FasterRCNN#4]
How to get predictions as a set of coordinates of marked segments - i.e. not as an segmented png-image but as e.g. json with:
```
{
  imageid: ccc;
  object:dog; 
  x1: 33;
  y1:44;
...
}

```

**Comment by trzy** [comment]
You just want the data dumped as JSON? Should be really easy but you’ll have to write it yourself. Look at how __main__.py works. Instead of rendering the outputs and writing image files, you could just append the results to an array of objects in whatever format you like and then dump it all as JSON at the end.

**Comment by trzy** [comment]
Specifically, look at predict(), predict_one(), and predict_all(). That’s where you’ll need to insert your own code. Play around with it and understand how the outputs are returned (everything should be documented or readable) and go from there. Instead of handing off to the visualize module, you can do whatever you want with the predictions.
